config/routes.rb
Rails.application.routes.draw do
  resources :companies
  devise_for :users
  get 'companies/index'
  root 'companies#index'

  resources :empresas
  resources :usuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /companies
  # GET /companies.json
  def index
    @companies = if params[:term]
    Company.where('name LIKE ?', "%#{params[:term]}%")
    else
      Company.all
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :country, :area, :description)
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario criado com sucesso.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuário alterado com sucesso.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuário deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:email, :senha)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/companies/_form.html.erb
<%= form_for(company) do |f| %>
<div class="container">
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>
      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field form-group">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>

  <div class="field form-group">
    <%= f.label :area %>
    <%= f.text_area :area %>
  </div>

  <div class="field form-group">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions form-group">
    <%= f.submit 'cadastrar', :class => 'btn btn-primary btn-sm' %>
  </div>
</div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editar empresa</h1>

<%= render 'form', company: @company %>
<%= link_to 'Mostrar', @company %> |
<%= link_to 'Voltar', companies_path %>

app/views/companies/index.html.erb
<div class="main-panel">
  <%= render partial: 'shared/navigation_search' %><br>
    <div class="main-panel-body">
      <% @companies.each do |company| %>
      <a><%= link_to company do %>
      <div class="card">     
        <div class="row">
          <div class="col-md-4">
            <%= image_tag "companies/img-e-1-lista@3x.png", class:"logo_companies" %>
          </div>               
          <div class="col-md-8 text-left">
            <div class="">
              <p>
                <span class="name"><%= company.name %></span><br>    
                <span class="area"><%= company.area %></span><br>
                <span class="country"><%= company.country %></span>  <br>        
              </p>        
            </div>
          </div>
        </div>
      </div>  
      </a>    
      <% end%>
      <% end %>
    </div>
  </div>      

app/views/companies/new.html.erb
<h1>Nova empresa</h1>
<%= render 'form', company: @company %>
<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<div class="main-panel">
  <%= render partial: 'shared/navigation_search' %>
  <div class="main-panel-body">
    <div class="card">     
      <div class="col-md-12 "><br>
        <%= image_tag "companies/img-e-1-lista@3x.png", class:"logo_companies" %>
      </div><br>
      <div class="col-md-12 text-left">
        <div class="description">
        <p><%=@company.description %></p>
        </div><br>
      </div>    
    </div>         
    <%= link_to 'Voltar', companies_path %><br>
  </div>
</div>      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kelly Ioasys</title>    
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
    <style type="text/css">
      @import url('//fonts.googleapis.com/css?family=Roboto');
    </style>
  </head>    
 
  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_navigation_search.html.erb
<div class="navbar" id="navbar">
<%= image_tag "logo-nav.png", class:" center-block logo-nav0", id:"logo-nav" %>
  <div class="container-2 right" id="notice">  
    <%= form_tag(companies_path, method: :get, class:'right') do %>
      <span class="icon"><i class="fa fa-search" id="search-icon"></i>&nbsp
        <%= text_field_tag :term %>
      </span> 
    <% end %>  
  </div>  
</div>

app/views/usuarios/_form.html.erb
<%= form_for(usuario) do |f| %>
  <% if usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :senha %>
    <%= f.password_field :senha %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Mostrar', @usuario %> |
<%= link_to 'Voltar', usuarios_path %>

app/views/usuarios/index.html.erb
  <div>
  <p id="notice"><%= notice %></p>
  <h1>Usuarios</h1>
  <table>
    <thead>
      <tr>
        <th>Email</th>
        <th>Senha</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @usuarios.each do |usuario| %>
        <tr>
          <td><%= usuario.email %></td>
          <td><%= usuario.senha %></td>
          <td><%= link_to 'Mostrar', usuario %></td>
          <td><%= link_to 'Editar', edit_usuario_path(usuario) %></td>
          <td><%= link_to 'Apagar', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Usuario', new_usuario_path %>
</div>

app/views/usuarios/new.html.erb
<h1>New Usuario</h1>
<%= render 'form', usuario: @usuario %>
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<p>
  <strong>Senha:</strong>
  <%= @usuario.senha %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<ul>    
    <li><%= link_to "usuários", usuarios_path %></li>
    <li><%= link_to "Empresas", companies_path %></li>
</ul>